'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
const ui={energy:energy,wave:wave,kills:kills,hp:castleHp,hpBar:castleHpBar,banner,toast,start:startScreen,pause:pauseScreen,end:endScreen};
const COLS=9,ROWS=5,CELL=94,OX=150,OY=94,FIELD_W=COLS*CELL,FIELD_H=ROWS*CELL;
const defs={
 sunny:{name:'Sunny',emoji:'🌻',role:'☀️',desc:'สร้างพลังงาน',cost:50,hp:105,rate:5900,cool:4200},
 peach:{name:'Peachy',emoji:'🍑',role:'🎯',desc:'ยิงแม่นยำ',cost:75,hp:120,rate:1250,damage:28,cool:3400,shot:'seed'},
 corn:{name:'Cobsworth',emoji:'🌽',role:'⚡',desc:'ยิงกระสุนคู่',cost:125,hp:135,rate:1050,damage:19,cool:5700,shot:'corn'},
 spud:{name:'Spud',emoji:'🥔',role:'🛡️',desc:'ป้องกันสูง',cost:100,hp:700,rate:0,cool:6200},
 chili:{name:'Inferno',emoji:'🌶️',role:'🔥',desc:'เผาทั้งแถว',cost:150,hp:1,rate:0,cool:10000,instant:'fire'},
 lily:{name:'Water Lily',emoji:'🪷',role:'❄️',desc:'ยิงชะลอ',cost:110,hp:115,rate:1500,damage:17,cool:5200,shot:'ice'},
 coconut:{name:'Coconut',emoji:'🥥',role:'💥',desc:'ยิงหนัก',cost:175,hp:220,rate:2400,damage:85,cool:7500,shot:'cannon'},
 mushroom:{name:'Laser Shroom',emoji:'🍄',role:'✨',desc:'ยิงทะลุ',cost:200,hp:100,rate:2100,damage:48,cool:9000,shot:'laser'}
};
const tray=document.getElementById('unitTray');Object.entries(defs).forEach(([id,d])=>tray.insertAdjacentHTML('beforeend',`<button class="unitCard" data-unit="${id}"><span class="role">${d.role}</span><span class="cost">${d.cost}</span><span class="sprite">${d.emoji}</span><b>${d.name}</b><small>${d.desc}</small><i class="cooldown"></i></button>`));
let S;
function reset(){S={running:false,paused:false,speed:1,energy:200,castleHp:100,wave:1,maxWave:10,kills:0,selected:null,hover:null,units:[],enemies:[],shots:[],fx:[],clouds:Array.from({length:12},(_,i)=>({x:i*112,y:28+(i%4)*28,s:28+(i%3)*10})),spawned:0,quota:7,nextSpawn:0,between:false,last:0,shake:0,cooldowns:Object.fromEntries(Object.keys(defs).map(k=>[k,0]))};updateUI()}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}
function txt(t,x,y,size=16,align='center'){ctx.font=`900 ${size}px ui-rounded,system-ui`;ctx.textAlign=align;ctx.textBaseline='middle';ctx.strokeStyle='#0a1020';ctx.lineWidth=Math.max(3,size/7);ctx.fillStyle='#fff';ctx.strokeText(t,x,y);ctx.fillText(t,x,y)}
function hpbar(x,y,w,p,color){rect(x,y,w,8,'#121a2e');rect(x+1,y+1,(w-2)*Math.max(0,p),6,color)}
function showBanner(t){ui.banner.textContent=t;ui.banner.classList.remove('hidden');clearTimeout(showBanner.t);showBanner.t=setTimeout(()=>ui.banner.classList.add('hidden'),1500)}
function showToast(t){ui.toast.textContent=t;ui.toast.classList.remove('hidden');clearTimeout(showToast.t);showToast.t=setTimeout(()=>ui.toast.classList.add('hidden'),1100)}
function updateUI(){ui.energy.textContent=Math.floor(S.energy);ui.wave.textContent=S.wave;ui.kills.textContent=S.kills;ui.hp.textContent=Math.max(0,Math.ceil(S.castleHp));ui.hpBar.style.width=Math.max(0,S.castleHp)+'%';document.querySelectorAll('.unitCard').forEach(c=>{const id=c.dataset.unit,d=defs[id],cd=Math.max(0,S.cooldowns[id]-performance.now());c.disabled=(S.energy<d.cost||cd>0)&&S.selected!==id;c.querySelector('.cooldown').style.height=(cd/d.cool*100)+'%';c.classList.toggle('selected',S.selected===id)})}
function drawWorld(ts){ctx.save();if(S.shake>0)ctx.translate((Math.random()-.5)*9,(Math.random()-.5)*9);const g=ctx.createLinearGradient(0,0,0,630);g.addColorStop(0,'#5abbe3');g.addColorStop(.55,'#d4f3d7');g.addColorStop(1,'#f7ebbd');ctx.fillStyle=g;ctx.fillRect(0,0,1120,630);S.clouds.forEach((c,i)=>{c.x=(c.x+.012*S.speed)%1260;rect(c.x-100,c.y,c.s*2,8,'#ffffffa8');rect(c.x-75,c.y-7,c.s,10,'#ffffffa8')});
// floating island and waterfall
rect(70,70,980,520,'#32483c');rect(82,83,956,495,'#88bf69');rect(96,560,928,20,'#51673e');for(let x=120;x<1010;x+=70)txt(x%140?'🌿':'🌼',x,575,17);rect(OX+FIELD_W+8,OY-3,86,FIELD_H+6,'#4d7e91');for(let y=OY;y<OY+FIELD_H;y+=24)rect(OX+FIELD_W+18,y,48,5,'#8fc4d5');
// castle
rect(92,110,49,405,'#593d2f');rect(98,123,37,380,'#e0bc7a');txt('🏰',116,292,52);txt('สวน',116,343,15);rect(88,500,57,14,'#3b2a25');
for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++){const x=OX+c*CELL,y=OY+r*CELL;rect(x,y,CELL-2,CELL-2,(r+c)%2?'#6eb75a':'#76c060');rect(x+7,y+8,5,5,'#a8df85');rect(x+CELL-16,y+CELL-17,4,4,'#4e8d42');if((r*COLS+c)%8===0)txt('✦',x+74,y+18,10)}
if(S.hover&&S.selected){const {r,c}=S.hover,occ=S.units.some(u=>u.r===r&&u.c===c);ctx.globalAlpha=.62;rect(OX+c*CELL+4,OY+r*CELL+4,CELL-10,CELL-10,occ?'#e95d62':'#fff169');ctx.globalAlpha=1;txt(defs[S.selected].emoji,OX+c*CELL+CELL/2,OY+r*CELL+52,45)}ctx.restore()}
function drawEntities(ts){S.units.forEach(u=>{const x=OX+u.c*CELL+CELL/2,y=OY+u.r*CELL+56,b=Math.sin(ts/220+u.c)*2;ctx.globalAlpha=u.hit>0?.45:1;txt('●',x,y+25,25);txt(u.emoji,x,y+b,u.type==='spud'?48:45);ctx.globalAlpha=1;hpbar(x-33,y-45,66,u.hp/u.maxHp,'#69df70')});S.enemies.forEach(e=>{const b=Math.sin(ts/130+e.x*.03)*3;ctx.save();ctx.translate(e.x,e.y+b);if(e.hit>0)ctx.globalAlpha=.42;rect(-25,-25,50,54,e.kind==='boss'?'#7f2b4d':e.kind==='brute'?'#68456f':e.kind==='mage'?'#354d78':'#3c465e');txt(e.kind==='boss'?'🐉':e.kind==='brute'?'👹':e.kind==='mage'?'🧙':'👾',0,-1,e.kind==='boss'?50:e.kind==='brute'?41:37);ctx.restore();hpbar(e.x-31,e.y-49,62,e.hp/e.maxHp,e.kind==='boss'?'#ffb640':'#ee6262')});S.shots.forEach(s=>{if(s.kind==='laser'){rect(s.x,s.y-3,34,6,'#f7ff9b');txt('✦',s.x+28,s.y,14)}else txt(s.kind==='corn'?'🌽':s.kind==='ice'?'❄️':s.kind==='cannon'?'🥥':'●',s.x,s.y,s.kind==='cannon'?23:18)});S.fx.forEach(p=>{ctx.globalAlpha=p.life/p.max;txt(p.t,p.x,p.y,p.size);ctx.globalAlpha=1})}
function spawnEnemy(){const r=Math.floor(Math.random()*ROWS),boss=S.wave===10&&S.spawned===S.quota-1,brute=!boss&&S.wave>=3&&Math.random()<.13+S.wave*.02,mage=!boss&&!brute&&S.wave>=5&&Math.random()<.15;const kind=boss?'boss':brute?'brute':mage?'mage':'bug',hp=(boss?1450:brute?290:mage?150:105)*(1+S.wave*.15),speed=boss?13:brute?18:mage?24:30+S.wave*1.1;S.enemies.push({r,x:OX+FIELD_W+50,y:OY+r*CELL+57,hp,maxHp:hp,speed,baseSpeed:speed,damage:boss?18:brute?12:mage?8:6,kind,hit:0,attackCd:0,slow:0,shootCd:1200});S.spawned++;if(boss)showBanner('⚠️ มังกรเงาปรากฏตัว!')}
function startWave(){S.between=false;S.spawned=0;S.quota=6+S.wave*2;S.nextSpawn=performance.now()+700;showBanner(`เวฟ ${S.wave} เริ่มแล้ว!`)}
function rowBlast(r){S.enemies.filter(e=>e.r===r).forEach(e=>{e.hp-=260+S.wave*14;e.hit=180});for(let c=0;c<COLS;c++)S.fx.push({x:OX+c*CELL+47,y:OY+r*CELL+50,t:'🔥',life:650,max:650,size:32});S.shake=380}
function update(dt,ts){if(!S.running||S.paused)return;dt*=S.speed;S.shake=Math.max(0,S.shake-dt);if(!S.between&&S.spawned<S.quota&&ts>=S.nextSpawn){spawnEnemy();S.nextSpawn=ts+Math.max(460,1350-S.wave*70)/S.speed}
S.units.forEach(u=>{u.hit=Math.max(0,u.hit-dt);u.timer-=dt;if(u.type==='sunny'&&u.timer<=0){S.energy+=28;u.timer=u.rate;S.fx.push({x:OX+u.c*CELL+47,y:OY+u.r*CELL+20,t:'+28☀️',life:700,max:700,size:15})}else if(u.rate&&u.timer<=0){const targets=S.enemies.filter(e=>e.r===u.r&&e.x>OX+u.c*CELL).sort((a,b)=>a.x-b.x);if(targets[0]){if(u.type==='mushroom'){targets.slice(0,3).forEach((e,i)=>{e.hp-=u.damage*(1-i*.18);e.hit=90});S.shots.push({r:u.r,x:OX+u.c*CELL+64,y:OY+u.r*CELL+52,damage:0,kind:'laser',speed:650,life:200})}else{const n=u.type==='corn'?2:1;for(let i=0;i<n;i++)S.shots.push({r:u.r,x:OX+u.c*CELL+66,y:OY+u.r*CELL+49+(i?10:-3),damage:u.damage,kind:u.shot,speed:u.type==='coconut'?260:390})}u.timer=u.rate}}});
S.shots.forEach(s=>{s.x+=s.speed*dt/1000;if(s.life){s.life-=dt;if(s.life<=0)s.dead=true;return}const e=S.enemies.find(e=>e.r===s.r&&Math.abs(e.x-s.x)<26);if(e){e.hp-=s.damage;e.hit=110;if(s.kind==='ice')e.slow=2100;if(s.kind==='cannon'){S.enemies.filter(x=>x.r===e.r&&Math.abs(x.x-e.x)<80).forEach(x=>x.hp-=35);S.fx.push({x:e.x,y:e.y,t:'💥',life:500,max:500,size:30});S.shake=100}s.dead=true;S.fx.push({x:e.x,y:e.y-8,t:'✦',life:330,max:330,size:14})}if(s.x>1090)s.dead=true});S.shots=S.shots.filter(s=>!s.dead);
S.enemies.forEach(e=>{e.hit=Math.max(0,e.hit-dt);e.attackCd-=dt;e.slow=Math.max(0,e.slow-dt);e.shootCd-=dt;const blocker=S.units.filter(u=>u.r===e.r&&Math.abs((OX+u.c*CELL+47)-e.x)<52).sort((a,b)=>b.c-a.c)[0];if(e.kind==='mage'&&e.shootCd<=0){const target=S.units.filter(u=>u.r===e.r).sort((a,b)=>b.c-a.c)[0];if(target){target.hp-=11;target.hit=130;S.fx.push({x:OX+target.c*CELL+47,y:OY+target.r*CELL+45,t:'⚡',life:350,max:350,size:21});e.shootCd=1900}}if(blocker){if(e.attackCd<=0){blocker.hp-=e.damage;blocker.hit=150;e.attackCd=e.kind==='boss'?500:780}}else e.x-=(e.slow>0?e.speed*.52:e.speed)*dt/1000;if(e.x<138){e.dead=true;S.castleHp-=e.kind==='boss'?38:e.kind==='brute'?16:8;S.shake=260;S.fx.push({x:140,y:e.y,t:'💥',life:650,max:650,size:34})}});
S.units=S.units.filter(u=>{if(u.hp<=0){S.fx.push({x:OX+u.c*CELL+47,y:OY+u.r*CELL+50,t:'💨',life:550,max:550,size:28});return false}return true});S.enemies.forEach(e=>{if(e.hp<=0){e.dead=true;S.kills++;const gain=e.kind==='boss'?120:e.kind==='brute'?24:e.kind==='mage'?18:12;S.energy+=gain;S.fx.push({x:e.x,y:e.y,t:`+${gain}☀️`,life:700,max:700,size:14})}});S.enemies=S.enemies.filter(e=>!e.dead);S.fx.forEach(p=>{p.life-=dt;p.y-=15*dt/1000});S.fx=S.fx.filter(p=>p.life>0);if(S.castleHp<=0)finish(false);if(!S.between&&S.spawned>=S.quota&&S.enemies.length===0){S.between=true;if(S.wave>=S.maxWave)finish(true);else{S.wave++;S.energy+=55;showBanner('เคลียร์เวฟ! +55 พลังงาน');setTimeout(()=>{if(S.running)startWave()},2100/S.speed)}}updateUI()}
function finish(win){S.running=false;endIcon.textContent=win?'🏆':'💔';endTitle.textContent=win?'ปกป้องสวนสำเร็จ!':'สวนถูกตีแตก';endText.textContent=win?`ผ่านครบ ${S.maxWave} เวฟ • กำจัด ${S.kills} ตัว`:`ไปถึงเวฟ ${S.wave} • กำจัด ${S.kills} ตัว`;ui.end.classList.remove('hidden')}
function loop(ts){const dt=Math.min(42,ts-(S.last||ts));S.last=ts;drawWorld(ts);update(dt,ts);drawEntities(ts);requestAnimationFrame(loop)}
function cellAt(ev){const b=canvas.getBoundingClientRect(),x=(ev.clientX-b.left)*canvas.width/b.width,y=(ev.clientY-b.top)*canvas.height/b.height,c=Math.floor((x-OX)/CELL),r=Math.floor((y-OY)/CELL);return r>=0&&r<ROWS&&c>=0&&c<COLS?{r,c}:null}
canvas.addEventListener('pointermove',e=>S.hover=cellAt(e));canvas.addEventListener('pointerleave',()=>S.hover=null);canvas.addEventListener('pointerdown',e=>{if(!S.running||S.paused)return;const cell=cellAt(e);if(!cell)return;const old=S.units.find(u=>u.r===cell.r&&u.c===cell.c);if(old){S.energy+=Math.floor(defs[old.type].cost*.4);S.units=S.units.filter(u=>u!==old);showToast(`ขาย ${old.name} แล้ว`);return}if(!S.selected)return;const d=defs[S.selected],now=performance.now();if(S.energy<d.cost){showToast('พลังงานไม่พอ');return}if(S.cooldowns[S.selected]>now){showToast('การ์ดยังไม่พร้อม');return}S.energy-=d.cost;S.cooldowns[S.selected]=now+d.cool;if(d.instant==='fire')rowBlast(cell.r);else S.units.push({type:S.selected,name:d.name,emoji:d.emoji,r:cell.r,c:cell.c,hp:d.hp,maxHp:d.hp,rate:d.rate,damage:d.damage||0,shot:d.shot,timer:250,hit:0});S.selected=null;updateUI()});
document.querySelectorAll('.unitCard').forEach(c=>c.onclick=()=>{if(!S.running)return;const id=c.dataset.unit,d=defs[id];if(S.energy<d.cost||S.cooldowns[id]>performance.now())return;S.selected=S.selected===id?null:id;updateUI()});
function begin(){reset();S.running=true;ui.start.classList.add('hidden');ui.end.classList.add('hidden');startWave()}
startBtn.onclick=begin;restartBtn.onclick=begin;pauseBtn.onclick=()=>{if(!S.running)return;S.paused=true;ui.pause.classList.remove('hidden')};resumeBtn.onclick=()=>{S.paused=false;S.last=performance.now();ui.pause.classList.add('hidden')};speedBtn.onclick=()=>{S.speed=S.speed===1?2:1;speedBtn.textContent='×'+S.speed;showToast(`ความเร็ว ×${S.speed}`)};window.addEventListener('keydown',e=>{if(e.key==='Escape'){S.selected=null;updateUI()}});reset();requestAnimationFrame(loop);
