'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
const ui={energy:document.getElementById('energy'),hp:document.getElementById('castleHp'),hpBar:document.getElementById('castleHpBar'),wave:document.getElementById('wave'),kills:document.getElementById('kills'),banner:document.getElementById('banner'),toast:document.getElementById('toast'),start:document.getElementById('startScreen'),end:document.getElementById('endScreen'),pause:document.getElementById('pauseScreen')};
const COLS=9,ROWS=5,CELL=82,OX=132,OY=67,LANE_H=82;
const unitsDef={sunny:{cost:50,hp:90,rate:6500,cool:4500,emoji:'🌻',name:'Sunny'},peach:{cost:75,hp:110,rate:1350,damage:24,cool:3500,emoji:'🍑',name:'Peachy'},corn:{cost:125,hp:125,rate:1050,damage:17,cool:6000,emoji:'🌽',name:'Cobsworth'},spud:{cost:100,hp:600,rate:0,cool:6500,emoji:'🥔',name:'Spud'},chili:{cost:150,hp:70,rate:0,cool:10500,emoji:'🌶️',name:'Inferno'}};
let state;
function reset(){state={running:false,paused:false,energy:175,castleHp:100,wave:1,maxWave:8,kills:0,selected:null,units:[],enemies:[],shots:[],particles:[],last:0,nextSpawn:0,spawned:0,waveQuota:6,between:false,cooldowns:{sunny:0,peach:0,corn:0,spud:0,chili:0},hover:null,shake:0};updateUI();}
function updateUI(){ui.energy.textContent=Math.floor(state.energy);ui.hp.textContent=Math.max(0,Math.ceil(state.castleHp));ui.hpBar.style.width=Math.max(0,state.castleHp)+'%';ui.wave.textContent=state.wave;ui.kills.textContent=state.kills;document.querySelectorAll('.unitCard').forEach(card=>{const d=unitsDef[card.dataset.unit],cd=Math.max(0,state.cooldowns[card.dataset.unit]-performance.now()),locked=state.energy<d.cost||cd>0;card.disabled=locked&&!card.classList.contains('selected');card.querySelector('.cooldown').style.height=(cd/d.cool*100)+'%';});}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h));}
function text(t,x,y,size=16,align='center'){ctx.font=`900 ${size}px ui-monospace,monospace`;ctx.textAlign=align;ctx.textBaseline='middle';ctx.fillStyle='#fff';ctx.strokeStyle='#11182b';ctx.lineWidth=Math.max(3,size/7);ctx.strokeText(t,x,y);ctx.fillText(t,x,y);}
function drawWorld(ts){ctx.save();if(state.shake>0)ctx.translate((Math.random()-.5)*8,(Math.random()-.5)*8);const sky=ctx.createLinearGradient(0,0,0,540);sky.addColorStop(0,'#5bb8dd');sky.addColorStop(.62,'#c5edcf');sky.addColorStop(1,'#eff7c9');ctx.fillStyle=sky;ctx.fillRect(0,0,960,540);for(let i=0;i<15;i++){const x=(i*149+ts*.012)%1120-80,y=24+(i%4)*31;rect(x,y,34+(i%3)*16,8,'#ffffff99');rect(x+9,y-5,24,7,'#ffffff99');}rect(0,500,960,40,'#6da36d');for(let i=0;i<12;i++)text(i%2?'☁️':'🌿',30+i*90,510+(i%2)*8,22);
 rect(0,36,110,460,'#516f47');rect(16,55,88,420,'#284532');rect(25,84,70,364,'#9a6039');rect(34,94,52,344,'#e7c98f');text('🏰',62,242,60);text('สวน',62,310,15);rect(22,416,76,12,'#4c3429');
 rect(OX-8,OY-8,COLS*CELL+16,ROWS*LANE_H+16,'#274f35');for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++){const x=OX+c*CELL,y=OY+r*LANE_H;rect(x,y,CELL-2,LANE_H-2,(r+c)%2?'#67ac54':'#72b85b');rect(x+5,y+6,5,5,'#98d77a');rect(x+CELL-15,y+LANE_H-13,4,4,'#4b883f');if((r*9+c)%7===0)text('✿',x+67,y+18,10);}rect(OX+COLS*CELL,OY-10,80,ROWS*LANE_H+20,'#476d7d');for(let y=OY;y<OY+ROWS*LANE_H;y+=28)rect(OX+COLS*CELL+10,y,50,5,'#79aabc');
 if(state.selected&&state.hover){const {r,c}=state.hover,occupied=state.units.some(u=>u.r===r&&u.c===c);ctx.globalAlpha=.58;rect(OX+c*CELL+4,OY+r*LANE_H+4,CELL-10,LANE_H-10,occupied?'#e65a5a':'#fff27a');ctx.globalAlpha=1;text(unitsDef[state.selected].emoji,OX+c*CELL+CELL/2,OY+r*LANE_H+44,42);}ctx.restore();}
function bar(x,y,w,p,c){rect(x,y,w,7,'#18223a');rect(x+1,y+1,(w-2)*Math.max(0,p),5,c);}
function drawEntities(ts){state.units.forEach(u=>{const x=OX+u.c*CELL+CELL/2,y=OY+u.r*LANE_H+47,bob=Math.sin(ts/220+u.c)*2;ctx.globalAlpha=u.hit>0?.5:1;text('●',x,y+25,24);text(u.emoji,x,y+bob,u.type==='spud'?45:43);ctx.globalAlpha=1;bar(x-30,y-39,60,u.hp/u.maxHp,'#65d46e');});state.enemies.forEach(e=>{const bob=Math.sin(ts/130+e.x*.03)*3;ctx.save();ctx.translate(e.x,e.y+bob);if(e.hit>0)ctx.globalAlpha=.42;rect(-24,-25,48,52,e.kind==='boss'?'#7e274c':e.kind==='brute'?'#6a3e6e':'#39445e');rect(-17,-33,34,15,e.kind==='boss'?'#d33e60':e.kind==='brute'?'#9b5ca2':'#687895');text(e.kind==='boss'?'🐲':e.kind==='brute'?'👹':'👾',0,-2,e.kind==='boss'?46:e.kind==='brute'?39:35);ctx.restore();bar(e.x-29,e.y-47,58,e.hp/e.maxHp,e.kind==='boss'?'#ffb13b':'#e65a5a');});state.shots.forEach(s=>{text(s.kind==='corn'?'🌽':s.kind==='fire'?'🔥':'●',s.x,s.y,s.kind==='fire'?25:18);});state.particles.forEach(p=>{ctx.globalAlpha=p.life/p.max;text(p.t,p.x,p.y,p.size);ctx.globalAlpha=1;});}
function spawnEnemy(){const r=Math.floor(Math.random()*ROWS),boss=state.wave===8&&state.spawned===state.waveQuota-1,brute=!boss&&state.wave>=3&&Math.random()<.17+state.wave*.02,hp=(boss?1100:brute?230:100)*(1+state.wave*.17),speed=boss?13:(brute?18:29)+state.wave*1.3;state.enemies.push({r,x:OX+COLS*CELL+58,y:OY+r*LANE_H+49,hp,maxHp:hp,speed,damage:boss?15:brute?10:6,kind:boss?'boss':brute?'brute':'bug',hit:0,attackCd:0});state.spawned++;if(boss)showBanner('⚠️ บอสแห่งเงาปรากฏตัว!');}
function startWave(){state.between=false;state.spawned=0;state.waveQuota=5+state.wave*2;state.nextSpawn=performance.now()+800;showBanner(`เวฟ ${state.wave} เริ่มแล้ว!`);}
function showBanner(msg){ui.banner.textContent=msg;ui.banner.classList.remove('hidden');setTimeout(()=>ui.banner.classList.add('hidden'),1550);}
function toast(msg){ui.toast.textContent=msg;ui.toast.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>ui.toast.classList.add('hidden'),1200);}
function boomRow(r){state.enemies.filter(e=>e.r===r).forEach(e=>{e.hp-=220+state.wave*12;e.hit=180;});for(let c=0;c<COLS;c++)state.particles.push({x:OX+c*CELL+40,y:OY+r*LANE_H+42,t:'🔥',life:700,max:700,size:30});state.shake=350;}
function update(dt,ts){if(!state.running||state.paused)return;state.shake=Math.max(0,state.shake-dt);if(!state.between&&state.spawned<state.waveQuota&&ts>=state.nextSpawn){spawnEnemy();state.nextSpawn=ts+Math.max(500,1420-state.wave*75);}state.units.forEach(u=>{u.hit=Math.max(0,u.hit-dt);u.timer-=dt;if(u.type==='sunny'&&u.timer<=0){state.energy+=25;u.timer=u.rate;state.particles.push({x:OX+u.c*CELL+42,y:OY+u.r*LANE_H+15,t:'+25☀️',life:700,max:700,size:14});}else if((u.type==='peach'||u.type==='corn')&&u.timer<=0){const target=state.enemies.filter(e=>e.r===u.r&&e.x>OX+u.c*CELL).sort((a,b)=>a.x-b.x)[0];if(target){const n=u.type==='corn'?2:1;for(let i=0;i<n;i++)state.shots.push({r:u.r,x:OX+u.c*CELL+62,y:OY+u.r*LANE_H+42+(i?8:-3),damage:u.damage,kind:u.type,speed:350});u.timer=u.rate;}}});state.shots.forEach(s=>{s.x+=s.speed*dt/1000;const e=state.enemies.find(e=>e.r===s.r&&Math.abs(e.x-s.x)<25);if(e){e.hp-=s.damage;e.hit=100;s.dead=true;state.particles.push({x:e.x,y:e.y-5,t:'✦',life:430,max:430,size:16});}if(s.x>940)s.dead=true;});state.shots=state.shots.filter(s=>!s.dead);state.enemies.forEach(e=>{e.hit=Math.max(0,e.hit-dt);e.attackCd-=dt;const blocker=state.units.filter(u=>u.r===e.r&&Math.abs((OX+u.c*CELL+42)-e.x)<49).sort((a,b)=>b.c-a.c)[0];if(blocker){if(e.attackCd<=0){blocker.hp-=e.damage;blocker.hit=140;e.attackCd=e.kind==='boss'?520:800;}}else e.x-=e.speed*dt/1000;if(e.x<105){e.dead=true;state.castleHp-=e.kind==='boss'?35:e.kind==='brute'?15:8;state.shake=250;state.particles.push({x:112,y:e.y,t:'💥',life:700,max:700,size:32});}});state.units=state.units.filter(u=>{if(u.hp<=0){state.particles.push({x:OX+u.c*CELL+42,y:OY+u.r*LANE_H+42,t:'💨',life:650,max:650,size:27});return false;}return true;});state.enemies.forEach(e=>{if(e.hp<=0){e.dead=true;state.kills++;state.energy+=e.kind==='boss'?100:e.kind==='brute'?22:12;state.particles.push({x:e.x,y:e.y,t:e.kind==='boss'?'+100☀️':'+'+(e.kind==='brute'?22:12)+'☀️',life:700,max:700,size:14});}});state.enemies=state.enemies.filter(e=>!e.dead);state.particles.forEach(p=>{p.life-=dt;p.y-=16*dt/1000;});state.particles=state.particles.filter(p=>p.life>0);if(state.castleHp<=0)finish(false);if(!state.between&&state.spawned>=state.waveQuota&&state.enemies.length===0){state.between=true;if(state.wave>=state.maxWave)finish(true);else{state.wave++;state.energy+=50;showBanner('เคลียร์เวฟ! +50 พลังงาน');setTimeout(()=>{if(state.running)startWave();},2400);}}updateUI();}
function finish(win){state.running=false;document.getElementById('endIcon').textContent=win?'🏆':'💔';document.getElementById('endTitle').textContent=win?'ปกป้องสวนสำเร็จ!':'สวนถูกตีแตก';document.getElementById('endText').textContent=win?`ผ่านครบ ${state.maxWave} เวฟ กำจัด ${state.kills} ตัว`:`ไปถึงเวฟ ${state.wave} กำจัด ${state.kills} ตัว`;ui.end.classList.remove('hidden');}
function loop(ts){const dt=Math.min(40,ts-(state.last||ts));state.last=ts;drawWorld(ts);update(dt,ts);drawEntities(ts);requestAnimationFrame(loop);}
function getCell(ev){const rct=canvas.getBoundingClientRect(),sx=canvas.width/rct.width,sy=canvas.height/rct.height,x=(ev.clientX-rct.left)*sx,y=(ev.clientY-rct.top)*sy,c=Math.floor((x-OX)/CELL),r=Math.floor((y-OY)/LANE_H);return r>=0&&r<ROWS&&c>=0&&c<COLS?{r,c}:null;}
canvas.addEventListener('pointermove',e=>state.hover=getCell(e));canvas.addEventListener('pointerleave',()=>state.hover=null);canvas.addEventListener('pointerdown',e=>{if(!state.running||state.paused)return;const cell=getCell(e);if(!cell)return;const old=state.units.find(u=>u.r===cell.r&&u.c===cell.c);if(old){state.energy+=Math.floor(unitsDef[old.type].cost*.4);state.units=state.units.filter(u=>u!==old);toast(`ขาย ${old.name} แล้ว`);return;}if(!state.selected)return;const d=unitsDef[state.selected],now=performance.now();if(state.energy<d.cost){toast('พลังงานไม่พอ');return;}if(state.cooldowns[state.selected]>now){toast('การ์ดยังไม่พร้อม');return;}state.energy-=d.cost;state.cooldowns[state.selected]=now+d.cool;if(state.selected==='chili'){boomRow(cell.r);}else state.units.push({type:state.selected,name:d.name,emoji:d.emoji,r:cell.r,c:cell.c,hp:d.hp,maxHp:d.hp,rate:d.rate,damage:d.damage||0,timer:250,hit:0});document.querySelectorAll('.unitCard').forEach(x=>x.classList.remove('selected'));state.selected=null;updateUI();});
document.querySelectorAll('.unitCard').forEach(card=>card.addEventListener('click',()=>{if(!state.running)return;const type=card.dataset.unit,d=unitsDef[type];if(state.energy<d.cost||state.cooldowns[type]>performance.now())return;const same=state.selected===type;document.querySelectorAll('.unitCard').forEach(x=>x.classList.remove('selected'));state.selected=same?null:type;if(!same)card.classList.add('selected');}));
function begin(){reset();state.running=true;ui.start.classList.add('hidden');ui.end.classList.add('hidden');startWave();}
document.getElementById('startBtn').onclick=begin;document.getElementById('restartBtn').onclick=begin;document.getElementById('pauseBtn').onclick=()=>{if(!state.running)return;state.paused=true;ui.pause.classList.remove('hidden');};document.getElementById('resumeBtn').onclick=()=>{state.paused=false;state.last=performance.now();ui.pause.classList.add('hidden');};window.addEventListener('keydown',e=>{if(e.key==='Escape'){state.selected=null;document.querySelectorAll('.unitCard').forEach(x=>x.classList.remove('selected'));}});reset();requestAnimationFrame(loop);
