'use strict';
const SAVE_KEY='orchardCampaignV1';
const HUB_KEY='orchardHubV1';
const $h=s=>document.querySelector(s);
function campaignSave(){try{return JSON.parse(localStorage.getItem(SAVE_KEY))||{unlocked:1,stars:{},gold:0}}catch{return{unlocked:1,stars:{},gold:0}}}
function hubSave(){try{return JSON.parse(localStorage.getItem(HUB_KEY))||{gems:25,claimed:false,quest:false,forge:0,energyBonus:0,skinOwned:false}}catch{return{gems:25,claimed:false,quest:false,forge:0,energyBonus:0,skinOwned:false}}}
function putHub(v){localStorage.setItem(HUB_KEY,JSON.stringify(v));refreshHub()}
function refreshHub(){const c=campaignSave(),h=hubSave(),starTotal=Object.values(c.stars||{}).reduce((a,b)=>a+b,0);$h('#goldText').textContent=c.gold||0;$h('#gemText').textContent=h.gems||0;$h('#levelText').textContent=`Lv.${1+Math.floor(starTotal/2)}`;$h('#questBadge').textContent=h.quest?'เสร็จแล้ว':'รับรางวัลได้';$h('#shopBadge').textContent=h.forge?'อัปเกรดแล้ว':'สินค้าใหม่'}
const positions={castle:[50,13],shop:[13,32],heroes:[76,30],forge:[17,61],quest:[75,58],reward:[59,73],home:[5,76],adventure:[42,76]};
let moving=false;
function movePlayer(place,after){const p=$h('#player'),pos=positions[place]||[48,63];moving=true;p.classList.add('walking');p.style.left=pos[0]+'%';p.style.top=pos[1]+'%';setTimeout(()=>{p.classList.remove('walking');moving=false;after&&after()},520)}
function openFeature(place){if(place==='adventure'){movePlayer(place,()=>{$h('#map').classList.add('show');renderMap()});return}movePlayer(place,()=>{const modal=$h('#buildingModal'),content=$h('#featureContent');content.innerHTML=featureHTML(place);modal.classList.add('show');bindFeature(place)})}
function featureHTML(place){const c=campaignSave(),h=hubSave();const defs={
 castle:`<h2>🏰 ปราสาทแห่งสวน</h2><p>ศูนย์บัญชาการของ Sky Kingdom</p><div class="feature-grid"><div><b>Chapter 1</b><small>ปลดล็อก ${c.unlocked||1}/3 ด่าน</small></div><div><b>ดาวรวม</b><small>${Object.values(c.stars||{}).reduce((a,b)=>a+b,0)} ⭐</small></div></div><button class="primary feature-action" data-action="map">เปิดแผนที่บท</button>`,
 shop:`<h2>🛒 ร้านค้าเมฆทอง</h2><p>แตะอ่านรายละเอียดก่อนซื้อ สินค้าถาวรจะมีผลกับทุกด่านทันที</p><div class="shop-list">
<div class="product-card ${h.energyBonus>=10?'owned':''}"><div class="product-head"><b>☀️ พลังงานเริ่มต้น +10</b><strong>100 Gold</strong></div><p class="product-desc"><b>ทำอะไรได้:</b> เพิ่มพลังงานตอนเริ่มด่านจากค่าปกติอีก 10 หน่วย ทำให้วาง Sunny หรือยูนิตตัวแรกได้เร็วขึ้น</p><div class="product-effect">ผลที่ได้รับ: +10 พลังงานเริ่มต้น • ถาวร • ใช้ได้ทุกด่าน</div><button class="buy-button" data-buy="energy" ${h.energyBonus>=10?'disabled':''}>${h.energyBonus>=10?'ซื้อแล้ว ✓ — กำลังใช้งาน':'ซื้อสินค้า'}</button></div>
<div class="product-card ${h.skinOwned?'owned':''}"><div class="product-head"><b>🎨 ชุดผู้พิทักษ์สวน</b><strong>150 Gold</strong></div><p class="product-desc"><b>ทำอะไรได้:</b> ปลดล็อกเครื่องแต่งกายสำหรับตัวละครผู้เล่นในเมืองลอยฟ้า ใช้เปลี่ยนรูปลักษณ์ใน Lobby</p><div class="product-effect">ผลที่ได้รับ: ชุดตกแต่ง 1 ชุด • ไม่มีผลต่อค่าพลังต่อสู้</div><button class="buy-button" data-buy="skin" ${h.skinOwned?'disabled':''}>${h.skinOwned?'ซื้อแล้ว ✓ — ปลดล็อกแล้ว':'ซื้อสินค้า'}</button></div>
</div>`,
 heroes:`<h2>🧙 ศาลาฮีโร่</h2><p>ตัวละครป้องกันที่ค้นพบแล้ว</p><div class="hero-list"><span>🌻<b>Sunny</b></span><span>🍑<b>Peachy</b></span><span>🌽<b>Cobsworth</b></span><span>🥔<b>Spud</b></span><span>🪷<b>Water Lily</b></span><span>🥥<b>Coconut</b></span><span>🍄<b>Laser Shroom</b></span></div>`,
 forge:`<h2>⚒️ โรงตีเหล็กใบไม้</h2><p>ระดับการอัปเกรดถาวร ${h.forge||0}/3</p><button class="primary feature-action" data-action="forge">อัปเกรดดาเมจ +5% • 120 Gold</button>`,
 quest:`<h2>📜 กระดานเควส</h2><div class="quest-card"><b>เควสประจำวัน</b><p>เข้าเยี่ยมเมืองลอยฟ้า 1 ครั้ง</p><small>รางวัล 50 Gold</small><button class="primary feature-action" data-action="quest" ${h.quest?'disabled':''}>${h.quest?'รับแล้ว':'รับรางวัล'}</button></div>`,
 reward:`<h2>🎁 ศูนย์รางวัล</h2><p>รางวัลล็อกอินประจำวัน</p><div class="daily-row"><span>วันที่ 1<br>🪙50</span><span>วันที่ 2<br>💎5</span><span>วันที่ 3<br>🎁</span></div><button class="primary feature-action" data-action="daily" ${h.claimed?'disabled':''}>${h.claimed?'รับวันนี้แล้ว':'รับรางวัลวันนี้'}</button>`,
 home:`<h2>🏡 บ้านผู้เล่น</h2><div class="feature-grid"><div><b>Gold</b><small>${c.gold||0}</small></div><div><b>Gem</b><small>${h.gems||0}</small></div><div><b>ด่านที่ปลดล็อก</b><small>${c.unlocked||1}/3</small></div><div><b>ดาวรวม</b><small>${Object.values(c.stars||{}).reduce((a,b)=>a+b,0)}</small></div></div><button class="feature-action" data-action="reset">รีเซ็ตข้อมูลทดสอบ</button>`};return defs[place]||'<h2>กำลังพัฒนา</h2>'}
function bindFeature(place){document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action,c=campaignSave(),h=hubSave();if(a==='map'){$h('#buildingModal').classList.remove('show');$h('#map').classList.add('show');renderMap()}if(a==='quest'&&!h.quest){h.quest=true;c.gold=(c.gold||0)+50;localStorage.setItem(SAVE_KEY,JSON.stringify(c));putHub(h);b.textContent='รับแล้ว';b.disabled=true}if(a==='daily'&&!h.claimed){h.claimed=true;c.gold=(c.gold||0)+50;localStorage.setItem(SAVE_KEY,JSON.stringify(c));putHub(h);b.textContent='รับวันนี้แล้ว';b.disabled=true}if(a==='forge'&&c.gold>=120&&h.forge<3){c.gold-=120;h.forge++;localStorage.setItem(SAVE_KEY,JSON.stringify(c));putHub(h);$h('#featureContent').innerHTML=featureHTML('forge');bindFeature('forge')}if(a==='reset'&&confirm('รีเซ็ตความคืบหน้าทั้งหมดหรือไม่?')){localStorage.removeItem(SAVE_KEY);localStorage.removeItem(HUB_KEY);location.reload()}});document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{const c=campaignSave(),h=hubSave(),item=b.dataset.buy;const price=item==='energy'?100:150;if((item==='energy'&&h.energyBonus>=10)||(item==='skin'&&h.skinOwned))return;if(c.gold<price){alert(`Gold ไม่เพียงพอ ต้องใช้ ${price} Gold`);return}c.gold-=price;if(item==='energy')h.energyBonus=10;if(item==='skin')h.skinOwned=true;localStorage.setItem(SAVE_KEY,JSON.stringify(c));putHub(h);$h('#featureContent').innerHTML=featureHTML('shop');bindFeature('shop')})}
function renderMap(){const s=campaignSave();$h('#progressText').textContent=`ปลดล็อก ${s.unlocked||1}/3 ด่าน • Gold ${s.gold||0}`;document.querySelectorAll('.stageCard').forEach(b=>{const n=Number(b.dataset.stage),locked=n>(s.unlocked||1),stars=(s.stars&&s.stars[n])||0;b.classList.toggle('locked',locked);b.disabled=locked;b.querySelector('.stars').textContent='★'.repeat(stars)+'☆'.repeat(3-stars);b.onclick=()=>{if(locked)return;localStorage.setItem('orchardCurrentStage',n);location.reload()}})}
document.querySelectorAll('[data-place]').forEach(b=>b.addEventListener('click',()=>!moving&&openFeature(b.dataset.place)));
$h('#closeFeature').onclick=()=>$h('#buildingModal').classList.remove('show');
$h('#closeMap').onclick=()=>{$h('#map').classList.remove('show')};
$h('#hubSound').onclick=e=>{e.currentTarget.textContent=e.currentTarget.textContent==='🔊'?'🔇':'🔊'};
const current=Number(localStorage.getItem('orchardCurrentStage')||0);if(current){$h('#hub').style.display='none';$h('#app').style.display='block';$h('#stageTitle').textContent=['','ด่าน 1 • สวนลอยฟ้า','ด่าน 2 • ป่าเวทมนตร์','ด่าน 3 • ภูเขาไฟลอยฟ้า'][current]}else{$h('#app').style.display='none'}
window.openCampaignMap=()=>{localStorage.removeItem('orchardCurrentStage');location.reload()};
$h('#mapBtn').onclick=()=>window.openCampaignMap();
refreshHub();renderMap();
